name: Build docs

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers workflow on every push to master branch
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: [self-hosted]

    env:
      DOXYFILE_NAME: "crypto3.doxyfile"
      DDOXYGEN_OUTPUT_DIR: "doxygen_build"
      BUILD_NAME: build_docs-${{ github.sha }}
      BUILD_ARCHIVE_NAME: build_docs-${{ github.sha }}.tar.gz

    steps:
      - name: Cleanup # TODO - move to scripts on runner
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cmake and build
        env:
          CMAKE_ARGS: "-DBUILD_SHARED_LIBS=TRUE -DBUILD_TESTS=TRUE -DDOXYGEN_OUTPUT_DIR=${{ env.DDOXYGEN_OUTPUT_DIR }}"
        run: |
          mkdir build
          cd build
          cmake ${{env.CMAKE_ARGS}} ..

      - name: Build doxygen
        working-directory: ./build
        run: doxygen ${{ env.DOXYFILE_NAME }}

      - name: Archive build results
        working-directory: ./build
        run: tar -czf ${{ env.BUILD_ARCHIVE_NAME }} -C ${{ env.DDOXYGEN_OUTPUT_DIR }} .

      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
          path: ./build/${{ env.BUILD_ARCHIVE_NAME }}
